### ISSUE TITLE
Is the GITHUB_WORKSPACE env required

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gogs#22]
I'm not sure we still used the `GITHUB_WORKSPACE` environment variable:
https://github.com/dwyl/gogs/blob/e41e7448413400fb6d94a8d8cf82de4a72afcb9d/lib/gogs_helpers.ex#L8

The only place we use it is here:
https://github.com/dwyl/gogs/blob/e41e7448413400fb6d94a8d8cf82de4a72afcb9d/lib/gogs_helpers.ex#L73-L81

Could we remove it completely?

**Comment by nelsonic** [comment]
@SimonLab great question. This was when I was trying to figure out running on GitHub CI ... 🙄 ⏳ 
Totally. can be removed now. Good spot! I have quite a few unstaged changes for #21 on my `localhost` ... 🧑‍💻 
Will remove this and push up changes soon.

**Comment by nelsonic** [comment]
P.S: are you attempting to get this running on your `localhost`? 💭  
(it' should all work but might have these kinds of "rough edges" ...) 🙃 
I'll be tiding/finishing: https://github.com/dwyl/gogs-demo later today. ⏳ 🧑‍💻 
Will be a _lot_ easier once there's a working demo. 😉

**Comment by SimonLab** [comment]
Yes I'm testing the gogs dependency on a new Phoenix application.
I have an issue with ssh but I don't think it's linked to any bugs/error in the code and more a configuration issue on my side

**Comment by nelsonic** [comment]
SSH issue debug log: https://github.com/dwyl/gogs-server/issues/2
