### ISSUE TITLE
Add dialyxir

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gogs#26]
Use dialyxir to detect errors in the code

see https://github.com/jeremyjh/dialyxir

At the moment running `mix dialyzer` returns
> Total errors: 7, Skipped: 0, Unnecessary Skips: 0

We could also run dialyzer on CI, however from https://github.com/jeremyjh/dialyxir#continuous-integration there are a few points to be aware of:
>
    Building the PLT file may take a while if a project has many dependencies
    The PLT should be cached using the CI caching system
    The PLT will need to be rebuilt whenever adding a new Erlang or Elixir version to build matrix

So it might be easier to run it on a pre-commit hook.

**Comment by nelsonic** [comment]
@SimonLab 100% up for running **`dialyzer`** on CI and even adding it as a `pre-commit` hook. 💭 
CI for now with an alias in the `mix.exs` so that it's easy to run. e.g. `mix d`

**Comment by SimonLab** [comment]
Continue to look at the dialyzer errors:
![image](https://user-images.githubusercontent.com/6057298/168048885-90678ec5-9467-4ec8-9c50-a2e9f650f48b.png)

**Comment by nelsonic** [comment]
Oh ... thanks. 👍

**Comment by SimonLab** [comment]
dialyzer has been added. Run `mix dialyzer` to check the code
